"""systemd rendering and installation helpers."""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Any

from arbor_ddns.config import AppConfig
from arbor_ddns.util.process import CommandNotFoundError, command_available, run_command
from arbor_ddns.workspace.models import ResolvedWorkspace, SystemdUnitStatus
from arbor_ddns.workspace.storage import WorkspacePaths


class SystemdError(RuntimeError):
    """Raised when a systemd operation fails."""


class SystemdManager:
    """Render and manage system-level workspace units."""

    def __init__(self, app_config: AppConfig | None = None) -> None:
        self._app_config = app_config or AppConfig.from_defaults()

    def render_service_unit(self, workspace: ResolvedWorkspace) -> str:
        """Render the systemd service unit text."""

        workspace_root = Path(workspace.workspace_root)
        exec_args = self._exec_start_args(workspace_root)
        exec_start = " ".join(_systemd_escape_arg(arg) for arg in exec_args)
        return (
            "# Generated by arbor-ddns. Do not edit by hand.\n"
            "[Unit]\n"
            f"Description=arbor-ddns sync for workspace {workspace.workspace_name}\n"
            "After=network-online.target\n"
            "Wants=network-online.target\n\n"
            "[Service]\n"
            "Type=oneshot\n"
            f"ExecStart={exec_start}\n\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n"
        )

    def render_timer_unit(self, workspace: ResolvedWorkspace) -> str:
        """Render the systemd timer unit text."""

        return (
            "# Generated by arbor-ddns. Do not edit by hand.\n"
            "[Unit]\n"
            f"Description=arbor-ddns timer for workspace {workspace.workspace_name}\n\n"
            "[Timer]\n"
            f"OnBootSec={workspace.systemd.on_boot_sec}\n"
            f"OnUnitActiveSec={workspace.systemd.on_unit_active_sec}\n"
            f"Unit={workspace.systemd.service_name}.service\n"
            "Persistent=true\n\n"
            "[Install]\n"
            "WantedBy=timers.target\n"
        )

    def install_rendered_units(
        self,
        paths: WorkspacePaths,
        workspace: ResolvedWorkspace,
    ) -> tuple[Path, Path]:
        """Install rendered unit files into the configured systemd directory."""

        unit_dir = self._app_config.systemd.resolved_unit_dir()
        unit_dir.mkdir(parents=True, exist_ok=True)
        installed_service = unit_dir / f"{workspace.systemd.service_name}.service"
        installed_timer = unit_dir / f"{workspace.systemd.timer_name}.timer"
        shutil.copy2(
            paths.rendered_systemd_dir / f"{workspace.systemd.service_name}.service",
            installed_service,
        )
        shutil.copy2(
            paths.rendered_systemd_dir / f"{workspace.systemd.timer_name}.timer",
            installed_timer,
        )
        return installed_service, installed_timer

    def daemon_reload(self) -> None:
        """Run `systemctl daemon-reload`."""

        run_command([self._app_config.systemd.systemctl_bin, "daemon-reload"])

    def enable_restart_timer(self, timer_name: str) -> None:
        """Enable and restart the timer unit."""

        systemctl = self._app_config.systemd.systemctl_bin
        run_command([systemctl, "enable", f"{timer_name}.timer"])
        run_command([systemctl, "restart", f"{timer_name}.timer"])

    def start_service(self, service_name: str) -> None:
        """Start a oneshot service immediately."""

        run_command([self._app_config.systemd.systemctl_bin, "start", f"{service_name}.service"])

    def status(self, unit_name: str, unit_kind: str) -> SystemdUnitStatus:
        """Return systemd status for one unit."""

        systemctl = self._app_config.systemd.systemctl_bin
        try:
            result = run_command(
                [
                    systemctl,
                    "show",
                    f"{unit_name}.{unit_kind}",
                    "--property=LoadState,UnitFileState,ActiveState,SubState,FragmentPath",
                ],
                check=False,
            )
        except CommandNotFoundError:
            return SystemdUnitStatus(
                unit_name=f"{unit_name}.{unit_kind}",
                available=False,
                note=f"{systemctl} is not available",
            )

        properties = _parse_systemd_show(result.stdout)
        return SystemdUnitStatus(
            unit_name=f"{unit_name}.{unit_kind}",
            available=True,
            load_state=_optional_text(properties.get("LoadState")),
            unit_file_state=_optional_text(properties.get("UnitFileState")),
            active_state=_optional_text(properties.get("ActiveState")),
            sub_state=_optional_text(properties.get("SubState")),
            fragment_path=_optional_text(properties.get("FragmentPath")),
            note=(
                None
                if result.returncode == 0
                else (result.stderr.strip() or result.stdout.strip() or None)
            ),
        )

    def systemctl_available(self) -> bool:
        """Return whether `systemctl` is available."""

        return command_available(self._app_config.systemd.systemctl_bin)

    def unit_dir_writable(self) -> bool:
        """Return whether the configured unit directory is writable."""

        unit_dir = self._app_config.systemd.resolved_unit_dir()
        target = unit_dir if unit_dir.exists() else unit_dir.parent
        return target.exists() and target.is_dir() and os_access_write(target)

    def _exec_start_args(self, workspace_root: Path) -> list[str]:
        console_script = shutil.which("arbor-ddns")
        if console_script is not None:
            return [console_script, "sync-once", "--workspace", str(workspace_root), "--apply"]
        return [
            str(Path(sys.executable).resolve()),
            "-m",
            "arbor_ddns.cli",
            "sync-once",
            "--workspace",
            str(workspace_root),
            "--apply",
        ]


def _parse_systemd_show(payload: str) -> dict[str, str]:
    properties: dict[str, str] = {}
    for line in payload.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        properties[key] = value
    return properties


def _optional_text(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None


def _systemd_escape_arg(value: str) -> str:
    return value.replace("\\", "\\\\").replace(" ", "\\x20")


def os_access_write(path: Path) -> bool:
    """Return whether the current process can write to a path."""

    return path.exists() and path.is_dir() and os.access(path, os.W_OK)
