"""systemd rendering and installation helpers."""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Any

from dnsleaf.util.process import (
    CommandNotFoundError,
    CommandResult,
    command_available,
    run_command,
)
from dnsleaf.workspace.models import ResolvedWorkspace
from dnsleaf.workspace.reports import SystemdUnitStatus
from dnsleaf.workspace.storage import WorkspacePaths


class SystemdError(RuntimeError):
    """Raised when a systemd operation fails."""


class SystemdManager:
    """Render and manage system-level workspace units."""

    def render_service_unit(self, workspace: ResolvedWorkspace) -> str:
        """Render the systemd service unit text."""

        workspace_root = Path(workspace.workspace_root)
        exec_args = self._exec_start_args(workspace_root)
        exec_start = " ".join(_systemd_escape_arg(arg) for arg in exec_args)
        return (
            "# Generated by dnsleaf. Do not edit by hand.\n"
            "[Unit]\n"
            f"Description=dnsleaf sync for workspace {workspace.workspace_name}\n"
            "After=network-online.target\n"
            "Wants=network-online.target\n\n"
            "[Service]\n"
            "Type=oneshot\n"
            f"ExecStart=:{exec_start}\n\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n"
        )

    def render_timer_unit(self, workspace: ResolvedWorkspace) -> str:
        """Render the systemd timer unit text."""

        return (
            "# Generated by dnsleaf. Do not edit by hand.\n"
            "[Unit]\n"
            f"Description=dnsleaf timer for workspace {workspace.workspace_name}\n\n"
            "[Timer]\n"
            f"OnBootSec={workspace.systemd.on_boot_sec}\n"
            f"OnUnitActiveSec={workspace.systemd.on_unit_active_sec}\n"
            f"Unit={workspace.systemd.service_name}.service\n"
            "Persistent=true\n\n"
            "[Install]\n"
            "WantedBy=timers.target\n"
        )

    def install_rendered_units(
        self,
        paths: WorkspacePaths,
        workspace: ResolvedWorkspace,
    ) -> tuple[Path, Path]:
        """Install rendered unit files into the configured systemd directory."""

        unit_dir = self._unit_dir(workspace)
        unit_dir.mkdir(parents=True, exist_ok=True)
        installed_service = unit_dir / f"{workspace.systemd.service_name}.service"
        installed_timer = unit_dir / f"{workspace.systemd.timer_name}.timer"
        shutil.copy2(
            paths.rendered_systemd_dir / f"{workspace.systemd.service_name}.service",
            installed_service,
        )
        shutil.copy2(
            paths.rendered_systemd_dir / f"{workspace.systemd.timer_name}.timer",
            installed_timer,
        )
        return installed_service, installed_timer

    def daemon_reload(self, workspace: ResolvedWorkspace, *, check: bool = True) -> CommandResult:
        """Run `systemctl daemon-reload`."""

        return run_command([self._systemctl_bin(workspace), "daemon-reload"], check=check)

    def enable_restart_timer(self, workspace: ResolvedWorkspace, timer_name: str) -> None:
        """Enable and restart the timer unit."""

        systemctl = self._systemctl_bin(workspace)
        run_command([systemctl, "enable", f"{timer_name}.timer"])
        run_command([systemctl, "restart", f"{timer_name}.timer"])

    def start_service(self, workspace: ResolvedWorkspace, service_name: str) -> None:
        """Start a oneshot service immediately."""

        run_command([self._systemctl_bin(workspace), "start", f"{service_name}.service"])

    def stop_service(
        self,
        workspace: ResolvedWorkspace,
        service_name: str,
        *,
        check: bool = False,
    ) -> CommandResult:
        """Stop a oneshot service if present."""

        return run_command(
            [self._systemctl_bin(workspace), "stop", f"{service_name}.service"],
            check=check,
        )

    def stop_timer(
        self,
        workspace: ResolvedWorkspace,
        timer_name: str,
        *,
        check: bool = False,
    ) -> CommandResult:
        """Stop a timer if present."""

        return run_command(
            [self._systemctl_bin(workspace), "stop", f"{timer_name}.timer"],
            check=check,
        )

    def disable_timer(
        self,
        workspace: ResolvedWorkspace,
        timer_name: str,
        *,
        check: bool = False,
    ) -> CommandResult:
        """Disable a timer if present."""

        return run_command(
            [self._systemctl_bin(workspace), "disable", f"{timer_name}.timer"],
            check=check,
        )

    def reset_failed(
        self,
        workspace: ResolvedWorkspace,
        unit_name: str,
        unit_kind: str,
        *,
        check: bool = False,
    ) -> CommandResult:
        """Clear retained failed state for one unit."""

        return run_command(
            [
                self._systemctl_bin(workspace),
                "reset-failed",
                f"{unit_name}.{unit_kind}",
            ],
            check=check,
        )

    def installed_unit_path(
        self,
        workspace: ResolvedWorkspace,
        unit_name: str,
        unit_kind: str,
    ) -> Path:
        """Return the configured installed unit path for one unit."""

        return self._unit_dir(workspace) / f"{unit_name}.{unit_kind}"

    def remove_installed_unit(
        self,
        workspace: ResolvedWorkspace,
        unit_name: str,
        unit_kind: str,
    ) -> Path | None:
        """Remove one installed unit file if present."""

        path = self.installed_unit_path(workspace, unit_name, unit_kind)
        if not path.exists():
            return None
        path.unlink()
        return path

    def status(
        self,
        workspace: ResolvedWorkspace,
        unit_name: str,
        unit_kind: str,
    ) -> SystemdUnitStatus:
        """Return systemd status for one unit."""

        systemctl = self._systemctl_bin(workspace)
        try:
            result = run_command(
                [
                    systemctl,
                    "show",
                    f"{unit_name}.{unit_kind}",
                    "--property=LoadState,UnitFileState,ActiveState,SubState,FragmentPath",
                ],
                check=False,
            )
        except CommandNotFoundError:
            return SystemdUnitStatus(
                unit_name=f"{unit_name}.{unit_kind}",
                available=False,
                note=f"{systemctl} is not available",
            )

        properties = _parse_systemd_show(result.stdout)
        return SystemdUnitStatus(
            unit_name=f"{unit_name}.{unit_kind}",
            available=True,
            load_state=_optional_text(properties.get("LoadState")),
            unit_file_state=_optional_text(properties.get("UnitFileState")),
            active_state=_optional_text(properties.get("ActiveState")),
            sub_state=_optional_text(properties.get("SubState")),
            fragment_path=_optional_text(properties.get("FragmentPath")),
            note=(
                None
                if result.returncode == 0
                else (result.stderr.strip() or result.stdout.strip() or None)
            ),
        )

    def systemctl_available(self, workspace: ResolvedWorkspace) -> bool:
        """Return whether `systemctl` is available."""

        return command_available(self._systemctl_bin(workspace))

    def unit_dir_writable(self, workspace: ResolvedWorkspace) -> bool:
        """Return whether the configured unit directory is writable."""

        unit_dir = self._unit_dir(workspace)
        target = unit_dir if unit_dir.exists() else unit_dir.parent
        return target.exists() and target.is_dir() and os_access_write(target)

    def _systemctl_bin(self, workspace: ResolvedWorkspace) -> str:
        return workspace.paths.systemctl_bin

    def _unit_dir(self, workspace: ResolvedWorkspace) -> Path:
        return workspace.paths.resolved_systemd_unit_dir()

    def _exec_start_args(self, workspace_root: Path) -> list[str]:
        return [
            os.path.abspath(sys.executable),
            "-m",
            "dnsleaf",
            "sync-once",
            "--workspace",
            str(workspace_root),
            "--apply",
        ]


def _parse_systemd_show(payload: str) -> dict[str, str]:
    properties: dict[str, str] = {}
    for line in payload.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        properties[key] = value
    return properties


def _optional_text(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None


def _systemd_escape_arg(value: str) -> str:
    """Quote for ExecStart=:, which disables environment expansion for all arguments."""

    if "\x00" in value:
        raise ValueError("systemd arguments must not contain NUL")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("%", "%%")
    escaped = "".join(
        f"\\x{ord(char):02x}" if ord(char) < 32 or ord(char) == 127 else char for char in escaped
    )
    return f'"{escaped}"'


def os_access_write(path: Path) -> bool:
    """Return whether the current process can write to a path."""

    return path.exists() and path.is_dir() and os.access(path, os.W_OK)
